@startuml
actor Usuario

Usuario -> Asignador: iniciarProceso()
Asignador -> Asignador: seleccionarPersonas()
Asignador -> Persona: crearListaPersonas()
Asignador -> Asignador: asignarInstrumentos()
Asignador -> Instrumento: crearListaInstrumentos()
Asignador -> Persona: asignarInstrumento()

note right of Asignador: Repite para cada persona seleccionada

Asignador --> Usuario: mostrarResultados()
@enduml