% database.pl
person('Alice', 30, 'Female').
person('Bob', 25, 'Male').
person('Charlie', 30, 'Male').
person('Dana', 28, 'Female').
person('Eve', 22, 'Female').
person('Frank', 40, 'Male').
person('wally', 22, 'male').
person('Alex', 34, 'male').
person('Jhonatan', 13, 'male').
person('Hank', 50, 'Male').
person('Ivy', 27, 'Female').
person('Jack', 33, 'Male').
person('Karen', 29, 'Female').
person('Leo', 38, 'Male').
person('Mona', 31, 'Female').
person('Nate', 42, 'Male').
person('Olivia', 26, 'Female').
person('Paul', 48, 'Male').
person('Rachel', 37, 'Female').
person('Steve', 41, 'Male').
person('Tina', 30, 'Female').
person('Uma', 29, 'Female').
person('Victor', 36, 'Male').
person('Wendy', 43, 'Female').
person('Xander', 39, 'Male').
person('Yara', 28, 'Female').
person('Zack', 44, 'Male').
person('Amy', 31, 'Female').
person('Ben', 27, 'Male').
person('Cara', 33, 'Female').
person('Dave', 46, 'Male').
person('Ella', 29, 'Female').
person('Finn', 32, 'Male').
person('Gina', 40, 'Female').
person('Hugo', 35, 'Male').
person('Isla', 30, 'Female').
person('Jake', 38, 'Male').
person('Kira', 28, 'Female').
person('Liam', 42, 'Male').
person('Mia', 31, 'Female').
person('Noah', 37, 'Male').
person('Opal', 34, 'Female').
